In [21]:
import pandas as pd

In [36]:
hist_fuel_costs = pd.read_csv('/Users/b1017579/Documents/PhD/Projects/10. ELECSIM/elecsim/data/fuel_data/fuel_costs/historical_fuel_cost_data/historical_fuel_costs.csv')

In [23]:
hist_fuel_costs = hist_fuel_costs.drop(['Unnamed: 0','Source','Units'], axis=1)
hist_fuel_costs

,Fuel,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Coal,0.006353,0.006259,0.006600,0.00611,0.00528,0.00500,0.00507,0.00474,0.00421,...,0.007534,0.008693,0.011096,0.009114,0.008424,0.007791,0.006693,0.007465,0.010159,0.009060
1,Oil,0.004457,0.004718,0.004813,0.00472,0.00526,0.00684,0.00709,0.00746,0.00599,...,0.022204,0.034873,0.044177,0.047985,0.044887,0.040530,0.027026,0.023931,0.030828,0.027480
2,Gas,0.005620,0.006070,0.005950,0.00556,0.00588,0.00584,0.00592,0.00593,0.00560,...,0.011350,0.013070,0.017110,0.021355,0.022993,0.018897,0.015855,0.012759,0.015241,0.018977
3,Uranium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003900
4,Diesel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.100000
5,Woodchip,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.025200
6,Poultry_litter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.011390
7,Straw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.016488
8,Meat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.010000
9,Waste_post_2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.025200
10,Waste_pre_2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.015510

In [32]:
hist_fuel_costs_long = pd.melt(hist_fuel_costs, id_vars=['Fuel'], var_name='Price', value_vars=list(hist_fuel_costs.loc[:,'1990':'2018'].columns))
hist_fuel_costs_long

                Fuel Price     value
0               Coal  1990  0.006353
1                Oil  1990  0.004457
2                Gas  1990  0.005620
3            Uranium  1990       NaN
4             Diesel  1990       NaN
5           Woodchip  1990       NaN
6     Poultry_litter  1990       NaN
7              Straw  1990       NaN
8               Meat  1990       NaN
9    Waste_post_2000  1990       NaN
10    Waste_pre_2000  1990       NaN
11              Coal  1991  0.006259
12               Oil  1991  0.004718
13               Gas  1991  0.006070
14           Uranium  1991       NaN
15            Diesel  1991       NaN
16          Woodchip  1991       NaN
17    Poultry_litter  1991       NaN
18             Straw  1991       NaN
19              Meat  1991       NaN
20   Waste_post_2000  1991       NaN
21    Waste_pre_2000  1991       NaN
22              Coal  1992  0.006600
23               Oil  1992  0.004813
24               Gas  1992  0.005950
25           Uranium  1992       NaN
26            Diesel  1992       NaN
27          Woodchip  1992       NaN
28    Poultry_litter  1992       NaN
29             Straw  1992       NaN
..               ...   ...       ...
289          Uranium  2016       NaN
290           Diesel  2016       NaN
291         Woodchip  2016       NaN
292   Poultry_litter  2016       NaN
293            Straw  2016       NaN
294             Meat  2016       NaN
295  Waste_post_2000  2016       NaN
296   Waste_pre_2000  2016       NaN
297             Coal  2017  0.010159
298              Oil  2017  0.030828
299              Gas  2017  0.015241
300          Uranium  2017       NaN
301           Diesel  2017       NaN
302         Woodchip  2017       NaN
303   Poultry_litter  2017       NaN
304            Straw  2017       NaN
305             Meat  2017       NaN
306  Waste_post_2000  2017       NaN
307   Waste_pre_2000  2017       NaN
308             Coal  2018  0.009060
309              Oil  2018  0.027480
310              Gas  2018  0.018977
311          Uranium  2018  0.003900
312           Diesel  2018  0.100000
313         Woodchip  2018  0.025200
314   Poultry_litter  2018  0.011390
315            Straw  2018  0.016488
316             Meat  2018  0.010000
317  Waste_post_2000  2018 -0.025200
318   Waste_pre_2000  2018 -0.015510

[319 rows x 3 columns]

In [35]:
hist_fuel_costs_long.to_csv('/Users/b1017579/Documents/PhD/Projects/10. ELECSIM/elecsim/data/fuel_data/fuel_costs/historical_fuel_cost_data/historical_fuel_costs_converted_long.csv')